### ISSUE TITLE
Align term encoding to TBX

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-model-iso#38]
Make sure that metanorma grammar can match the expressive power of TBX, http://www.tbxinfo.net, and that there is a 1:1 mapping between Metanorma and TBX. (I would rather we not embed TBX inside Metanorma.)

**Comment by ronaldtse** [comment]
We need to do something here; our favorite format does embed TBX.

**Comment by opoudjis** [comment]
> We need to do something here

Yes. We need to get more resources, or reduce scope. Otherwise, tickets will continue to be unactioned for years.

**Comment by opoudjis** [comment]
I'll add that duplicating an existing well-founded grammar seems to be inane, if we can just add it as an alternative. NISO have done so.

**Comment by ronaldtse** [comment]
Agree, we can accept TBX. But you mentioned not wanting to embed?

**Comment by opoudjis** [comment]
A minor nuisance compared to the inanity of duplicating TBX.

**Comment by opoudjis** [comment]
Is this ticket superseded by https://github.com/metanorma/metanorma-standoc/issues/255 (and at most reviewing it against TBX)?

**Comment by ronaldtse** [comment]
Yes indeed. Closing in favor of new issue.
