### ISSUE TITLE
What should put into NIST editorialgroup?

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-model-iso#42]
I'm trying to update NistBib according to the last changes in `nist.rnc`.
We have authors in `contributor` now. Maybe we should move them to `editorialgroup`. If no what should we put into `editorialgroup`?

**Comment by opoudjis** [comment]
Leave it empty. I thought "Information Security" was an editorial group, as in a technical committee; but as far as I can tell, NIST (or at least NIST 800, which is the only bit we're working with) does not have those.

DO NOT MOVE AUTHORS INTO EDITORIAL GROUP. That is where Metanorma expects to find them.
