### ISSUE TITLE
Move bibliographic item models and grammars to relaton-models

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-iso#68]
Too confusing: https://github.com/ietf-ribose/relaton-data-3gpp/issues/5#issuecomment-996677486

**Comment by ronaldtse** [comment]
* [ ] Move away 3GPP bibliographic models to relaton-model-3gpp
* [ ] Move away BIPM bibliographic models to relaton-model-bipm
* [ ] Move away BSI bibliographic models to relaton-model-bsi
* [ ] Move away CSA bibliographic models to relaton-model-csa
* [ ] Move away GB bibliographic models to relaton-model-gb
* [ ] Move away CC/CalConnect bibliographic models to relaton-model-cc
* [ ] Move away IEC bibliographic models to relaton-model-iec
* [ ] Move away IETF bibliographic models to relaton-model-ietf
* [ ] Move away IHO bibliographic models to relaton-model-iho
* [ ] Move away ISO bibliographic models to relaton-model-iso
* [ ] Move away ITU bibliographic models to relaton-model-itu
* [ ] Move away M3AAWG bibliographic models to relaton-model-m3aawg
* [ ] Move away MPFA bibliographic models to relaton-model-mpfa
* [ ] Move away NIST bibliographic models to relaton-model-nist
* [ ] Move away OGC bibliographic models to relaton-model-ogc
* [ ] Move away Ribose bibliographic models to relaton-model-ribose
* [ ] Move away UN bibliographic models to relaton-model-un

**Comment by opoudjis** [comment]
all done ages ago
