### ISSUE TITLE
Undefined flavor grammars

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-model-iso#75]
The following repos are empty:

- https://github.com/relaton/relaton-model-cie
- https://github.com/relaton/relaton-model-ecma
- https://github.com/relaton/relaton-model-iana

There is also relaton-omg gem. We don't have model repo for it and I'm not sure if we need.

**Comment by ronaldtse** [comment]
Yes we will need a model repo and the grammar for it. Thanks!

**Comment by andrew2net** [comment]
@opoudjis I'm sorry, I missed OASIS. It has the model repo https://github.com/relaton/relaton-model-oasis but the `grammars/relaton-oasis.rng` and `grammars/relaton-oasis-compile.rng` files aren't compliled.

**Comment by opoudjis** [comment]
Done
