### ISSUE TITLE
Issue with submodules

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-model-iso#79]
On a fresh cloned the repo I went to the `grammar` and run `sh make.sh` and got the error:
```sh
sh make.sh
Already up to date.
Updating submodules...
make.sh: line 12: cd: relaton-models/grammars: No such file or directory
...
```
The line 12 in make.sh file

https://github.com/metanorma/metanorma-model-iso/blob/4e74338fc22ee4acc55bb1ba897c2cfce1817833/grammars/make.sh#L12

It seems we need to pull the submodules. The make.sh has `git submodule update` command

https://github.com/metanorma/metanorma-model-iso/blob/4e74338fc22ee4acc55bb1ba897c2cfce1817833/grammars/make.sh#L8

But it does nothing because submodules are not initialized and their directories are empty. I suppose we should use `git submodule update --init --remote`.

**Comment by opoudjis** [comment]
@andrew2net If you don't add issues to the Metanorma project, it will be months before I notice them.

This is not an issue with submodules, this is git 101; see e.g. https://gist.github.com/gitaarik/8735255 for a tutorial. Closing in favour of https://github.com/metanorma/metanorma-model-iso/issues/78 , and https://github.com/metanorma/metanorma-model-iso/issues/78 is going to be very brief indeed.
